### ISSUE TITLE
データ設計としてデータベース・データソース設計をする

### ISSUE THREAD

**Issue by maeda-m** [maeda-m/employmate#10]
開発者として設計したい。それはモデルやコントローラーの実装に影響するためだ。

https://bootcamp.fjord.jp/practices/229

用語辞典をもとにする。イミュータブルデータモデルや楽々ERDレッスンにあるように6W3Hで整理したイベントとリソースに分けて考える。

具体的には次の流れでER図（IE記法）にまとめる。

1. エンティティの候補（何について記録したいのか）を洗い出す
    - 6W3Hによる整理をする
    - イベント系（～するもしくは～日という表現が成立する）かリソース系（～名の意味が通る）かをあわせて整理する
    - 記録したいものかを判断する
2. イベント系に対する正規化を行なって、リソース系を洗い出す
    - One fact in one place を前提に洗い出す
3. リソース系に対する分類の洗い出しを行なって、リソース系の正規化を行なう
    - 区分（感覚的な分類）や種類（共通した性質での分類）などの分類もあわせて洗い出す
4. 性能のことは置いておいて、冗長な項目を削除する
    - 導出系（View のような）エンティティを設けるのも可
5. 非依存のリレーションシップ（時限NULL）がある場合は、イベントが隠れているため洗い出す

データーベースに関しては、ER図（IE記法）を [mermaid](https://github.com/mermaid-js/mermaid) で記述します。
一部データについては、YAMLで扱う想定であるためデータ構造を実例で示します。

---

### ER図の凡例

```mermaid
---
title: 【図】ER図の凡例
---
erDiagram

entity_name1 {
  column_type primary_key_name PK "主キー名"
  column_type foreign_key_name FK "外部キー名1"
  column_type column_name "カラム名1"
}

entity_name2 {
  column_type primary_key_name PK "主キー名"
  column_type foreign_key_name FK "外部キー名1"
  column_type column_name "カラム名1"
  column_type column_name "カラム名2"
}

entity_name3 {
  column_type primary_key_name PK "主キー名"
  column_type foreign_key_name FK "外部キー名1"
  column_type foreign_key_name FK "外部キー名2"
}

entity_name1 ||--|{ entity_name3 : "依存リレーションシップ名"
entity_name2  ||..o{ entity_name3 : "非依存リレーションシップ名"

```

### column_type の意味

次の [データ型](https://www.postgresql.jp/document/14/html/datatype.html) を想定しています。

|column_type |データ型|
|:--------------|:----|
|string         |上限付き可変長文字列|
|text           |制限なし可変長文字列|
|integer        |4バイト符号付き整数|
|bigint         |8バイト符号付き整数|
|bigserial      |自動増分8バイト整数|
|datetime       |日付と時刻（時間帯なし）|
|date           |日付（時刻なし）|
|boolean        |論理値（真/偽）|

---

**参考情報**

* https://twitter.com/kawasima/status/1531430479223992320
* https://bootcamp.fjord.jp/products/12075
* https://github.com/kufu/activerecord-bitemporal
* https://www.slideshare.net/kawasima/ss-40471672
* https://www.slideshare.net/kawasima/ss-44958468
* https://speakerdeck.com/kawasima/lu-li-wochi-tudetafalseshe-ji
* https://www.slideshare.net/kawasima/ss-250716400
* [イミュータブルデータモデル - kawasima](https://scrapbox.io/kawasima/%E3%82%A4%E3%83%9F%E3%83%A5%E3%83%BC%E3%82%BF%E3%83%96%E3%83%AB%E3%83%87%E3%83%BC%E3%82%BF%E3%83%A2%E3%83%87%E3%83%AB)
* https://speakerdeck.com/masuda220/table-design
* https://astah.change-vision.com/ja/manual/455-erd.html
* https://blog.agile.esm.co.jp/entry/rails-polymorphic-story
* https://qiita.com/ysn/items/01c1f849d801fab54956
* https://qiita.com/hirokidaichi/items/61ad129eae43771d0fc3
* https://qiita.com/takasek/items/70ab5a61756ee620aee6
* https://qiita.com/a-suenami/items/de7e3dc0ee91910c8b3d
* https://speakerdeck.com/ymiyake/sql-training-2021?slide=7
* https://speakerdeck.com/ymiyake/sql-training-2021?slide=78
* https://dbconcept.hatenablog.com/entry/2021/10/02/160925

---

**参考書籍**

* 失敗から学ぶRDBの正しい歩き方
* WEB+DB PRESS Vol.130 のデータモデリング
* 楽々ERDレッスン

**Comment by maeda-m** [comment]
エレベーターピッチやペーパープロトタイプの要件をまとめると次の機能的な表現となります。

- ユーザーは事情（退職日、病気やケガの状況、直近の残業時間）や技能習得希望有無の調査に回答すると、回答結果（診断ではなく情報提供のため）として状況に合った雇用保険制度（基本手当または受給期間延長の推奨、公共職業訓練の推奨）がわかる。
- ユーザーは回答結果に関連したやることリストとハローワークに持っていく文書・証書、概算の給付金振り込み予定日 [^90] がわかる。
- ユーザーは会員登録すると、やることリストのタスクを完了でき、概算より正確な暫定・確定の給付金振り込み予定日がわかる。
- ユーザーはログインすると、やることリストのタスクの状態が前回から維持され、概算より正確な暫定・確定の給付金振り込み予定日がわかる。
- ユーザーは勤務していた会社から発行された離職票を受け取った後 [^96] にハローワークで離職票と求職票（＋雇用保険制度によって添付文書・証書あり）を提出する。
その時、 **離職票が受理される** と、ユーザーは雇用保険の失業等給付受給資格者のしおりを受け取る。
- ユーザーは雇用保険の失業等給付受給資格者のしおりに記載されている、雇用保険説明会日、初回失業認定日、失業認定日の型、失業認定日の曜日の調査に回答すると、給付金振り込み予定日 [^91] が暫定になる。
- ユーザーは雇用保険説明会に出席したとき、ハローワークから受給資格決定通知として **雇用保険受給者証が交付される** 。そのときに（仮）の有無を回答する。
  - （仮）があれば給付要件を満たしていないため、やることリストのタスクが追加される。
    - ユーザーは初回失業認定日またはその翌日以降に雇用保険受給者証が再交付され、（仮）が外れる。
    そこに記載されている、離職理由コード、雇用保険受給者証の交付日の調査に回答すると、給付金振り込み予定日 [^92] が確定する。
  - （仮）がなければ給付要件を満たしたものとして扱う
    - ユーザーは雇用保険受給者証に記載されている離職理由のコードの調査に回答すると、給付金振り込み予定日 [^93] が確定する。
- ユーザーはやることリストのタスクがすべて完了すると、今後3カ月の失業認定日 [^94] と給付金振り込み予定日 [^94] が確定する。

[^90]: 退職日から概算の失業認定日と待機期間、暫定の給付制限 [^95] 、行政機関の開庁日から計算する。
[^91]: 初回失業認定日と待機期間、暫定の給付制限 [^95] 、行政機関の開庁日から計算する。
[^92]: 初回失業認定日または雇用保険受給者証の交付日と待機期間、離職理由コードから確定した給付制限、行政機関の開庁日から計算する。
[^93]: 初回失業認定日と待機期間、離職理由コードから確定した給付制限、行政機関の開庁日から計算する。
[^94]: 初回失業認定日と待機期間、離職理由コードから確定した給付制限、認定日の型、認定日の曜日、行政機関の開庁日から計算する。
[^95]: 回答結果から特定受給資格者（再就職の準備をする時間的余裕なく離職を余儀なくされた方）または特定理由離職者（正当な理由がある退職者）に該当しそうかを判断する。
[^96]: 退職日の翌日から10日前後までに発行する法令となっている。

機能的な表現を 6W3H で整理し、記録したいもののみにすると下表のとおりとなりました。

|6W3H |分類|エンティティ候補|
|:----|:---|:---------------|
|Whom |リソース系（誰に）||
|Who  |リソース系（誰が）|ユーザー|
|What |リソース系（何を、対象）|調査、回答結果、退職日、受給期間延長を推奨、公共職業訓練を推奨、やることリスト、雇用保険説明会の日、初回失業認定日、失業認定日の型、失業認定日の曜日、離職理由コード、特定受給資格者、特定理由離職者|
|Where|リソース系（どこ）||
|How  |イベント系（どのように、手段、操作）|回答する、タスクを完了する|
|When |属性の候補またはリソース系（いつ、予定や期間を除く日付や日時）||
|How many |属性の候補またはリソース系（どれくらい、数量）||
|How much |属性の候補またはリソース系（いくら、金額）||
|Why  |イベント系（業務に起因するなぜ、理由）|離職票の受理、雇用保険受給者証の交付|

上記のほかに [アプリケーション的な用語](https://github.com/maeda-m/employmate/blob/main/docs/%E7%94%A8%E8%AA%9E%E8%BE%9E%E5%85%B8.md) から質問に関するものや区分や種類をリソース系として扱います。

**Comment by maeda-m** [comment]
## ER図

実体関連モデルをER図（IE記法）で整理しました。

```mermaid
---
title: 【図】雇用保険給付の相棒（Employmate）のER図
---
erDiagram

users {
  bigserial id PK "ID"
  string google_id "Open ID で取得した Google ID をハッシュ化したもの"
  datetime created_at "会員登録日時"
}
profiles {
  bigserial id PK "ID"
  bigint user_id FK "ユーザーID"
  date unemployed_on "退職日"
  boolean recommended_to_extension_of_benefit_receivable_period "受給期間延長を推奨"
  boolean recommended_to_public_vocational_training "公共職業訓練を推奨"
  boolean unemployed_with_special_eligible "特定受給資格者"
  boolean unemployed_with_special_reason "特定理由離職者"
  date explanitory_seminar_on_for_employment_insurance "雇用保険説明会の日"
  date first_unemployment_certification_on "初回失業認定日"
  string week_type_for_unemployment_certification "失業認定日の型"
  string day_of_week_for_unemployment_certification "失業認定日の曜日"
  string reason_code_for_loss_of_employment "離職理由コード"
}

"surveys.yml"
questionnaires {
  bigserial id PK "ID"
  bigint survey_id FK "調査ID"
  string title "件名"
  integer position "表示順"
}
questions {
  bigserial id PK "ID"
  bigint questionnaire_id FK "質問票ID"
  string body "本文"
  string answer_component_type "回答形式"
  boolean required "必須"
  integer position "表示順"
}
answer_conditions {
  bigserial id PK "ID"
  bigint question_id FK "質問ID"
  boolean every "毎回表示"
  boolean answered "回答があるとき表示"
  boolean equal "回答が等しいとき表示"
  bigint condition_question_id FK "表示条件に指定する回答の質問ID"
  string condition_answer_value "表示条件に指定する回答の値"
}

tasks {
  bigserial id PK "ID"
  bigint user_id FK "ユーザーID"
  bigint task_category_id FK "やることの種類ID"
  bigint survey_id FK "やること完了前にする調査ID"
  boolean done "完了"
  integer position "表示順"
  datetime created_at "作成日時"
  datetime updated_at "完了日時"
}

answers {
  bigserial id PK "ID"
  bigint user_id FK "ユーザーID"
  bigint survey_id FK "回答結果作成のための調査ID"
  date created_at "回答日時"
}
approvals {
  bigserial id PK "ID"
  bigint user_id FK "ユーザーID"
  date created_on "受理日"
}
issuances {
  bigserial id PK "ID"
  bigint user_id FK "ユーザーID"
  boolean done "（仮）"
  date created_on "交付日"
}

users ||--|| profiles : "回答結果"
users ||--|{ answers : "回答履歴"
users ||--o{ approvals : "受理履歴"
users ||--o{ issuances : "交付履歴"
"surveys.yml" ||--|{ questionnaires : "質問票"
questionnaires ||--|{ questions : "質問"
questions ||--|| "answer_components.yml" : "回答形式"
questions ||--|| answer_conditions : "質問の表示条件"
answer_conditions ||..o| questions : "表示条件に指定する回答の質問"

users ||--|{ tasks : "やることリスト"
tasks ||--|| "task_categories.yml" : "やることの種類"
tasks ||--o| "surveys.yml" : "やること完了前にする調査"
answers ||--|| "surveys.yml" : "回答結果作成のための調査"

```

## YAML

YAMLで定義したデータは固定値として組み込みます。
https://github.com/active-hash/active_hash でデータソースとして扱います。

### surveys.yml

質問票をとりまとめる調査です。

```yaml
# 回答結果作成のための調査
- id: 1
  name: 初回分析
  survey_type: profile

# やること完了前にする調査
- id: 2
  name: 離職票の受理
  survey_type: task
- id: 3
  name: 雇用保険受給者証の交付
  survey_type: task
```

### task_categories.yml

やることの種類です。

```yaml
- id: 1
  name: いますぐ
  label_attribute:
- id: 2
  name: 退職日の翌日
  label_attribute: unemployed_on
  label_suffix: 以降
- id: 3
  name: 離職票発行日
  label_attribute: issuanced_on_of_release_form
  label_suffix: 頃
- id: 4
  name: 雇用保険説明会日
  label_attribute: explanitory_seminar_on_for_employment_insurance
  label_suffix: 頃
- id: 5
  name: 初回失業認定日
  label_attribute: first_unemployment_certification_on
  label_suffix: の週
```

### answer_components.yml

質問の回答形式です。
https://github.com/ViewComponent/view_component でHTMLを管理するため、対応するクラスの紐づけに使用します。

```yaml
- id: 1
  type: yes_or_no
  name: はい／いいえ
- id: 2
  type: yes_or_no_with_not_applicable
  name: はい／いいえ／わからない
- id: 3
  type: date
  name: 年月日
- id: 4
  type: month
  name: 年月
- id: 5
  type: overtime
  name: 残業時間（整数）
- id: 6
  type: week_type
  name: 失業認定日の型
- id: 7
  type: day_of_week
  name: 失業認定日の曜日
- id: 8
  type: reason_code
  name: 離職理由コード

```
