### ISSUE TITLE
開発環境を構築する

### ISSUE THREAD

**Issue by maeda-m** [maeda-m/employmate#20]
### ユーザーストーリー

開発者として構築したい。
それは本番環境と同等の構成で開発したいからだ。

### 受け入れ条件

- [x] `docker-compose up` でAP（Puma）、DB（PostgreSQL）が稼働すること
- [x] Dockerfile で極端なエラーがないこと
  - https://github.com/hadolint/hadolint
  - https://hadolint.github.io/hadolint/
- [x] Secretlint を導入する
  - https://efcl.info/2020/03/24/secretlint/
- [x] READMEに追記する
  - 簡単なシステム構成図（システムコンテキスト図）を記載すること
  - 開発環境の立ち上げ手順を記載すること
    - `docker compose up -d`
    - `docker compose exec rails bash`
    - `bin/setup`
      - `npm install-clean` も
    - `bin/dev`
- [x] 開発用の設定をすること
  - https://github.com/active-hash/active_hash
  - https://github.com/palkan/view_component-contrib
  - https://github.com/dtaniwaki/rack-dev-mark
  - https://github.com/flyerhzm/bullet
  - https://techlife.cookpad.com/entry/2021/12/27/202133
  - https://github.com/rails/web-console
  - `config/database.yml` を変更しなくても `ENV['DATABASE_URL']` で接続できるようにする
    - https://edgeguides.rubyonrails.org/configuring.html#configuring-a-database

### もしできたらうれしいこと

- [x] `docker-compose up` でWeb（Nginx）が稼働し、静的ファイルの配信ができること
  - https://github.com/maeda-m/employmate/issues/56 の検証になる
  - https でアクセスできること（DNSチャレンジとかでSSLサーバー証明書を作成する）
  - `docker-compose.yml` には含めず、個別でWebサーバーを起動してAPにリダイレクトさせる
    - DNSチャレンジができないときも考慮してオプションとして起動できる扱いとする

---

**参考情報**

- https://esa-pages.io/p/sharing/4060/posts/3072/e373619a15af8f160961.html
- https://github.com/moby/buildkit/blob/dockerfile/1.4.3/frontend/dockerfile/docs/syntax.md
- https://fly.io/ruby-dispatch/rails-on-docker/

**Comment by maeda-m** [comment]
Nginx で受け付けし、リバースプロキシでDocker 上で稼働する Rails アプリケーションに https でアクセスできた。
ただし、 config ファイルの環境変数管理が [envsubst](https://book.st-hakky.com/docs/how-to-use-env-var-nginx/) などを活用しないと難しそうだったため、コミットせず、このコメントに例を記載する。

> **Note**
> 
> HTTP/2 の設定、静的ファイルのキャッシュやセキュリティ対策、その他DDos攻撃対策やphpファイルなどのアクセスブロックなどは未チェックなので、あくまでもローカルで https による検証がしたいときだけ使うこと

### DNSのAレコードやTXTレコードを設定できること

独自ドメインを取得しており、 `localhost.example.com` などにAレコードとして `127.0.0.1` を設定していること。

**参考情報**

- https://letsencrypt.org/ja/docs/certificates-for-localhost/
- https://blog.jxck.io/entries/2020-06-29/https-for-localhost.html

### https 用の docker compose ファイルを別途作成すること

`https-compose.yml` など、既存の `docker-compose.yml` と別のファイルを作成する（同じでもいいが、管理がしやすいため別ファイルにする）。

```yaml
version: '3.8'

services:
  # See: https://hub.docker.com/_/nginx
  nginx:
    restart: 'no'
    volumes:
      - .nginx/conf.d:/etc/nginx/conf.d
      - .nginx/letsencrypt:/etc/letsencrypt
    image: nginx:1.24-bullseye
    ports:
      - "443:443"

  # See: https://hub.docker.com/r/certbot/certbot
  certbot:
    restart: 'no'
    volumes:
      - .nginx/conf.d:/etc/nginx/conf.d
      - .nginx/letsencrypt:/etc/letsencrypt
    image: certbot/certbot:v2.5.0
    command: '--help'

```

### Let’s Encrypt の DNS チャレンジを使用して証明書を取得すること

次のコマンドで証明書を取得する。

`docker compose -f https-compose.ym run certbot certonly --register-unsafely-without-email --agree-tos --preferred-challenges=dns --manual`

**参考情報**

- https://eff-certbot.readthedocs.io/en/stable/install.html#alternative-1-docker
- https://certbot.eff.org/instructions?ws=nginx&os=debianbuster

### Rails アプリケーションのローカルIPアドレスを確認すること

`docker-compose exec rails bash` を実行してから `cat /etc/hosts` で確認できる。
もし必要なら [ping](https://packages.debian.org/ja/sid/iputils-ping) や [ipadd](https://packages.debian.org/sid/iproute2) をインストールして疎通確認をします。

### config ファイルを作成していること

`default.conf`

```conf
server {
  listen 443 ssl;
  server_name 独自ドメイン;
  root /usr/share/nginx/html;
  location @application_server {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://RailsアプリケーションのローカルIPアドレス:3000;
  }

  location / {
    try_files $uri @application_server;
  }

  ssl_certificate /etc/letsencrypt/live/独自ドメイン/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/独自ドメイン/privkey.pem;

  ssl_session_cache shared:le_nginx_SSL:10m;
  ssl_session_timeout 1440m;
  ssl_session_tickets off;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
}

server_tokens off;

```

**参考情報**

- https://zenn.dev/junki555/articles/4848fe33909741ff811b
- https://osusublog.net/?p=965

### Rails アプリケーションの接続許可ホスト名を追加していること

```diff
@ -67,4 +67,5 @@ Rails.application.configure do
    Bullet.bullet_logger = true
    Bullet.add_footer = true
  end
+  config.hosts << "独自ドメイン"
end
```

以上の設定で自己証明書など不要な https でアクセスできる。
